version: '3.8'

services:
  spring-boot-app:
    container_name: dockerapp_container
    image: dockerapp.jar
    build: ./
    ports:
      - "9090:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres_db:5432/employeedb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: java@2021
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgresql_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: java@2021
      POSTGRES_DB: employeedb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
